name: via_strengths_analysis
dependencies:
- python=3.5
- matplotlib=3.0.0
- jupyter
- numpy=1.15.2
- scipy=1.1.0
- scikit-learn
- nb_conda
- pandas
- networkx
- pip:
        - opencv-contrib-python==4.0.0.21
        - nelson
